version: "3.7"
services:
  app:
    build:
      args:
        user: sheye
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sheye
    container_name: sheye-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - storage:/var/www/html/storage
    ports:
      - 80:80
    networks:
      - sheye-network

  db:
    image: mariadb:10.2
    container_name: sheye-db
    restart: on-failure
    environment:
      MYSQL_DATABASE: scanner
      MYSQL_ROOT_PASSWORD: scanner
      MYSQL_PASSWORD: scanner
      MYSQL_USER: scanner
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - sheye-network

networks:
  sheye-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
  storage:
    driver: local